### ISSUE TITLE
A Sponsors bar - How do we add that?

### ISSUE THREAD

**Issue by benkrogh-zz** [benkrogh-zz/ADF#3]
He wants to have a way to add a bar with sponsor logos on the homepage. How do we go about doing this where he can add it later?

It would be great to have him be able to add a few logo jpgs or .pngs. Not sure how feasible it is, let me know.

**Comment by joshrounsville** [comment]
@benkrogh 
This is in place between the videos and instagram feed - http://adf.joshrounsville.com/

The sponsorship page mentions large, medium, and small logo placement on the homepage. Should we setup a specific layout for different sponsorship levels? Let me know if you have any feedback!

**Comment by joshrounsville** [comment]
@benkrogh 
And should the logos link someplace??
