### ISSUE TITLE
Board of Directors bios and information

### ISSUE THREAD

**Issue by benkrogh-zz** [benkrogh-zz/ADF#4]
We still need to update the Board of Directors page. 

The content for the board of directors page can be found here: https://docs.google.com/document/d/1yicgxyJO-EDV63YisgktB8sz_YByu1jOx9oxkxkQfWo/edit?usp=sharing

We can add placehold.it images for board members we don't have images for until Joaquim provides.

**Comment by joshrounsville** [comment]
@benkrogh 

Pending member images and titles
