### ISSUE TITLE
Email Address information

### ISSUE THREAD

**Issue by benkrogh-zz** [benkrogh-zz/ADF#5]
Here are the email addresses to use for the contact page and international contact link in the footer:

Email Address info:
JB Cunha -      Jbcunha-jb@futeboltraining.com
Chris Thurley - christ@futeboltraining.com
Wandi Ali - wandi@futeboltraining.com 
Joaquim Capuia - joaquim@futeboltraining.com 
staff@futeboltraining.com ( General Allies that forwards to Joaquim )
team@futeboltraining.com ( Emails to all team members above including staff ) 

International Exchange: 
exchange@futeboltraining.com ( international email address )

**Comment by joshrounsville** [comment]
@benkrogh 

Can you review this one - http://adf.joshrounsville.com/about/contact/

I removed Gracy Mosquera, Foday Kabba, & Sorin Popovich and added the title of Coach to Chris Thurley & Wandi Ali.

**Comment by benkrogh-zz** [comment]
I think this is good. I'm going to send him the site for final review. So if it's missing anything he'll let us know.
